<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'OjUserRbacDoctrineORM\Module'                                    => __DIR__ . '/Module.php',
  'OjUserRbacDoctrineORM\Entity\UserRoleLinker'                     => __DIR__ . '/src/OjUserRbacDoctrineORM/Entity/UserRoleLinker.php',
  'OjUserRbacDoctrineORM\Factory\ModuleOptionsFactory'              => __DIR__ . '/src/OjUserRbacDoctrineORM/Factory/ModuleOptionsFactory.php',
  'OjUserRbacDoctrineORM\Factory\UserRoleLinkerMapperFactory'       => __DIR__ . '/src/OjUserRbacDoctrineORM/Factory/UserRoleLinkerMapperFactory.php',
  'OjUserRbacDoctrineORM\Mapper\Exception\InvalidArgumentException' => __DIR__ . '/src/OjUserRbacDoctrineORM/Mapper/Exception/InvalidArgumentException.php',
  'OjUserRbacDoctrineORM\Mapper\UserRoleLinkerMapper'               => __DIR__ . '/src/OjUserRbacDoctrineORM/Mapper/UserRoleLinkerMapper.php',
  'OjUserRbacDoctrineORM\Options\ModuleOptions'                     => __DIR__ . '/src/OjUserRbacDoctrineORM/Options/ModuleOptions.php',
);
